# Generated by Django 4.2.9 on 2024-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_home', models.TextField(blank=True, null=True)),
                ('country_away', models.TextField(blank=True, null=True)),
                ('score_home', models.TextField(blank=True, null=True)),
                ('score_away', models.TextField(blank=True, null=True)),
                ('flag_home', models.TextField(blank=True, null=True)),
                ('flag_away', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('winner', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
    ]
